import { Product, Category, Testimonial } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'all',
    name: 'Todos',
    description: 'Toda nuestra gama tecnológica de vanguardia.',
    icon: 'Grid',
    count: 8,
    gradient: 'from-blue-600 via-indigo-600 to-purple-600',
    shadowColor: 'rgba(59, 130, 246, 0.4)',
  },
  {
    id: 'smartphones',
    name: 'Celulares',
    description: 'Dispositivos de última generación con pantallas OLED y chips neuronales.',
    icon: 'Smartphone',
    count: 3,
    gradient: 'from-cyan-500 to-blue-600',
    shadowColor: 'rgba(6, 182, 212, 0.4)',
  },
  {
    id: 'accessories',
    name: 'Accesorios',
    description: 'Cargadores GaN ultrarrápidos, protectores premium y fundas magnéticas.',
    icon: 'Headphones',
    count: 3,
    gradient: 'from-purple-500 to-pink-600',
    shadowColor: 'rgba(168, 85, 247, 0.4)',
  },
  {
    id: 'gadgets',
    name: 'Gadgets Tech',
    description: 'Smartwatches, visores de realidad virtual y teclados mecánicos cyberpunk.',
    icon: 'Cpu',
    count: 2,
    gradient: 'from-amber-400 to-orange-500',
    shadowColor: 'rgba(245, 158, 11, 0.4)',
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 'phone-01',
    name: 'Nebula X Alpha',
    category: 'smartphones',
    price: 1199,
    originalPrice: 1349,
    description: 'El buque insignia del futuro. Pantalla LTPO AMOLED holográfica de 6.9", procesador NeuralCore v4 y cámara de visión cuántica nocturna.',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
    tags: ['Nuevo', 'Hot'],
    specs: ['Snapdragon 9 Gen 4', '16GB RAM / 1TB SSD', 'Cámara 200MP + Térmica', 'Batería Grafeno 5500 mAh'],
    features: ['Conectividad Satelital', 'Zoom Óptico 10x', 'Pantalla Enrollable', 'Carga Solar Sutil'],
    inStock: true,
    isNew: true
  },
  {
    id: 'phone-02',
    name: 'Titanium Pro Max S',
    category: 'smartphones',
    price: 999,
    description: 'La elegancia hecha metal. Chasis de titanio de grado aeroespacial, refrigeración líquida de cámara de vapor y pantalla de 144Hz.',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    tags: ['Recomendado'],
    specs: ['Bionic A18 Cyber', '12GB LPDDR5X RAM', 'Sensor de 1" Sony LYT', 'Chasis Titanio Pulido'],
    features: ['Escaner LiDAR 3D', 'MagSafe Avanzado', 'Resistencia IP69K', 'Audio Espacial 3D'],
    inStock: true
  },
  {
    id: 'phone-03',
    name: 'AeroFold Nova',
    category: 'smartphones',
    price: 1499,
    originalPrice: 1699,
    description: 'El smartphone plegable definitivo. Grosor récord de 4.8mm abierto, bisagra de fricción cero y pliegue invisible con cristal ultradelgado.',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    tags: ['Plegable', 'Oferta'],
    specs: ['Dual-Display OLED', '16GB RAM / 512GB', 'Plegable 360 grados', 'Triple Cámara Ultra slim'],
    features: ['Plegado Perfecto', 'Modo Flex de Escritorio', 'Cargador 100W Incluido', 'Lápiz Óptico AeroPen'],
    inStock: true,
    isNew: false
  },
  {
    id: 'acc-01',
    name: 'AeroBuds Quantum',
    category: 'accessories',
    price: 189,
    originalPrice: 249,
    description: 'Audio inmersivo puro. Cancelación de ruido activa adaptativa inteligente de 52dB con traductores automáticos por IA en tiempo real.',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    tags: ['Best Seller', 'Descuento'],
    specs: ['Drivers Duales Coaxiales', 'ANC Inteligente 52dB', 'Batería 40h de autonomía', 'Audio ID Adaptativo'],
    features: ['IPX7 a Sudor', 'Traductor Offline a 24 Idiomas', 'Latencia de Juego ultra-baja', 'Doble Emparejamiento Multipunto'],
    inStock: true,
    isNew: true
  },
  {
    id: 'acc-02',
    name: 'HyperCharge GaN Pro',
    category: 'accessories',
    price: 59,
    description: 'Estación de carga miniatura de nitruro de galio (GaN) con tres puertos USB-C y USB-A. Carga tu laptop y smartphone simultáneamente a 140W.',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1622445262465-2481c4574875?auto=format&fit=crop&w=800&q=80',
    tags: ['Imprescindible'],
    specs: ['Potencia total 140W', 'Tecnología GaN V5', 'Protección térmica activa', 'Diseño compacto plegable'],
    features: ['Reparto inteligente inteligente', 'Chip PowerSafe', 'Compatible con PD 3.1', 'Indicador Amperaje LED'],
    inStock: true
  },
  {
    id: 'acc-03',
    name: 'MagShield Armor S',
    category: 'accessories',
    price: 39,
    description: 'Funda de fibra de aramida Kevlar ligera de grado antibalas con imanes ultra fuertes N52 para montaje magnético seguro y disipación de calor activa.',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1608156639585-b3a032ef9689?auto=format&fit=crop&w=800&q=80',
    tags: ['Resistente'],
    specs: ['Fibra Kevlar Premium', 'Imanes N52 Neodimio', 'Bordes de TPU Absorbente', 'Protección cámara de aluminio'],
    features: ['Estructura Panal Disipadora', 'Agarre antideslizante', 'Compatible con todos soportes Qi2', 'Garantía de Por Vida'],
    inStock: true
  },
  {
    id: 'gadget-01',
    name: 'CyberWatch Series X',
    category: 'gadgets',
    price: 349,
    originalPrice: 399,
    description: 'Tu asistente de biohacker definitivo. Con monitorización continua de glucosa no invasiva, ECG, VO2 Max y mapas vectoriales satelitales sin conexión.',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    tags: ['Avanzado', 'Nuevo'],
    specs: ['Pantalla Retina Zafiro', 'Carcasa de Titanio/Carbono', 'Duración batería 14 días', 'GPS de doble frecuencia'],
    features: ['Sensor de Glucosa por Espectrometría', 'Entrenador Deportivo IA integrado', 'Sincronización de Mapas GPX', 'Modo Buceo Profesional IP68'],
    inStock: true,
    isNew: true
  },
  {
    id: 'gadget-02',
    name: 'OmniLens Glass VR',
    category: 'gadgets',
    price: 699,
    description: 'El futuro de la informática espacial. Visor VR/AR ultra compacto y ligero de 280g con pantallas Micro-OLED 4K duales y seguimiento ocular fluido.',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=800&q=80',
    tags: ['Premium'],
    specs: ['Resolución Dual Ultra-4K', 'Seguimiento Ocular 90Hz', 'Procesador M-Space AR', 'Cámaras Pass-Through Ultra HD'],
    features: ['Sistemas de Audio Periférico', 'Ajuste Electrónico de Dioptrías', 'Control de Gestos sin mandos', 'Conectividad WiFi 7 / 5G Dual'],
    inStock: true
  },
  {
    id: 'phone-s25',
    name: 'Samsung Galaxy S25 Ultra Combo',
    category: 'smartphones',
    price: 1499,
    originalPrice: 1599,
    description: '¡Super Combo Especial Limitado! Llévate el nuevo Samsung Galaxy S25 Ultra y te regalamos una magnífica Smart TV de 32" HD de forma totalmente gratuita y automática.',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
    tags: ['Combo Súper Regalo', 'Hot'],
    specs: ['Snapdragon 8 Gen 4', 'S-Pen Integrado', 'Cámara 200MP Zoom 100x', 'Pantalla QHD+ Dynamic OLED'],
    features: ['Smart TV 32" HD REGALO', 'Envío Priority Súper Rápido', 'Garantía Oficial 24 meses', 'Pago Contra Entrega disponible'],
    inStock: true,
    isNew: true
  },
  {
    id: 'phone-iphone16',
    name: 'iPhone 16 Pro Max Combo',
    category: 'smartphones',
    price: 1399,
    originalPrice: 1499,
    description: 'La combinación perfecta de Apple de grado Pro. Comprando tu iPhone 16 Pro Max de Titanio te obsequiamos los AirPods Pro 2 gratis para disfrutar del sonido inmersivo espacial.',
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80',
    tags: ['Combo Apple', 'Destacado'],
    specs: ['Chip A18 Pro 3nm', 'Chasis de Titanio Grado 5', 'Botón Control de Cámara', 'Sonido Dolby Atmos'],
    features: ['AirPods Pro 2 REGALO', 'Envío Express de Cargo', 'Garantía certificada Apple 24 meses', 'Embalaje original sellado'],
    inStock: true,
    isNew: true
  },
  {
    id: 'phone-rog',
    name: 'ROG Phone 8 Pro Gamer Combo',
    category: 'smartphones',
    price: 999,
    originalPrice: 1199,
    description: 'El kit gamer elite definitivo para juegos móviles competitivos. Incluye el poderoso ASUS ROG Phone 8 Pro más el mando táctil ajustable GamePad Bluetooth oficial de regalo.',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?auto=format&fit=crop&w=800&q=80',
    tags: ['Combo Gamer', 'Recomendado'],
    specs: ['Snapdragon 9 Gen 3', 'Pantalla AMOLED 165Hz', 'Gatillos AirTrigger IA', 'Refrigeración Líquida'],
    features: ['GamePad Bluetooth REGALO', 'Disfraz Térmico de Refrigeración', 'Asistente de Audio Espacial DTS', 'Carga ultra de 65W'],
    inStock: true,
    isNew: true
  },
  {
    id: 'gadget-watch-combo',
    name: 'CyberWatch X Urban Combo',
    category: 'gadgets',
    price: 349,
    originalPrice: 538,
    description: 'La conexión inteligente urbana impecable. LLévate el CyberWatch Series X cargado de biosensores y te obsequiamos los auriculares inalámbricos con cancelación de ruido AeroBuds Quantum.',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    tags: ['Combo Inteligente', 'Hot Deal'],
    specs: ['GPS Satelital Offline', 'ECG y Glucómetro Biosensor', 'Resistencia IP68 Buceo', 'Llamadas Bluetooth HD'],
    features: ['AeroBuds Quantum REGALO', 'Medidor de estrés inteligente', 'Carga magnética flash', 'Sincronización total iOS/Android'],
    inStock: true,
    isNew: true
  },
  {
    id: 'phone-fold-combo',
    name: 'AeroFold Nova Power Combo',
    category: 'smartphones',
    price: 1499,
    originalPrice: 1699,
    description: 'El smartphone plegable extraordinario AeroFold Nova junto con la estación de carga de Nitruro de Galio HyperCharge GaN de 140W incluida sin costo adicional. Carga rápida absoluta.',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    tags: ['Combo Plegable', 'Premium'],
    specs: ['Bisagra Fricción Cero', 'Pantallas Duales 120Hz', 'Carga Simultánea 140W', 'Grosor increíble de 4.8mm'],
    features: ['Cargador GaN 140W REGALO', 'Lápiz AeroPen incluido', 'Doble Pantalla Cristal Ultrafino', 'Funda de aramida templada'],
    inStock: true,
    isNew: false
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't-01',
    name: 'Carlos Mendoza',
    role: 'Tech Enthusiast & Beta Tester',
    comment: 'Compré el Nebula X Alpha y la experiencia de compra fue increíble. El envío llegó en menos de 24 horas y empaquetado como si fuera una obra de arte del futuro. Excelente atención.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80',
    rating: 5
  },
  {
    id: 't-02',
    name: 'Sofía Valenzuela',
    role: 'Diseñadora Digital',
    comment: 'La estética de los productos y la calidad es indiscutible. El CyberWatch superó mis expectativas de diseño y rendimiento de batería. Sin duda volveré a comprar aquí.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80',
    rating: 5
  },
  {
    id: 't-03',
    name: 'Martín Silva',
    role: 'Desarrollador de software',
    comment: 'Me encanta que todos los accesorios cuenten con los mejores estándares como disipación activa y Kevlar. El cargador GaN 140W es súper compacto y carga toda mi estación de trabajo.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
    rating: 4
  }
];
